#-------------------------------
# Site Settings

title: Alexia Buclet
logo: # You can add own logo. For example '/images/logo.png'.
description: Senior UX / Product Manager & DesignOps Freelance For Good
meta_description: "UX Designer et Product Manager freelance, j‚Äôaccompagne les startups √† impact pour concevoir des produits et services utiles, durables et adopt√©s naturellement."
meta_title: "UX / PM freelance pour startups √† impact - Alexia Buclet"

menu__settings:
  menu__items:
    - title: 'Home'
      url: '/'
    #- title: 'Experience'
    #  url: '/projects/'
    - title: 'Exp√©riences'
      url: '/experiences/'
    - title: 'Speaker'
      url: '/speaker/'
    - title: 'Qui suis-je ?'
      url: '/about/'
    #- title: 'Pages'
    #  submenu:
    #  - url: '/about'
    #    title: 'About'
    #  - url: '/elements'
    #    title: 'Elements'

# Call to action button
cta__button__text: Contact

# Add global cover image (This field adds a background to the top and bottom of the site.)
#cover__image: '/images/378.jpg'


#-------------------------------
# Author Settings

author:
  name: Alexia Buclet
  title: Alexia Buclet
  bio: Senior UX Designer / Product Manager <br>Freelance For Good pour Produits / Services √† Impact üåç
  image: '/images/alexia-buclet.jpg'
  image_alt: "Photo d'Alexia Buclet"
  avatar: '/images/avatar.jpg'
  button__text: TO DEFINE
  # button in HTML

#-------------------------------
# T√©moignages

testimonials:
  testimonial__title: "Ils m'ont fait confiance"
  testimonials_items:
    - name: 
      #designation: 
      content: "Le taff effectu√© pendant la mission a √©t√© top, bluffant et hyper utile !"
      #image: 
    - name: 
      #designation: 
      content: "Son expertise et sa capacit√© √† piloter des projets complexes ont √©t√© impressionnants. C'est un r√©el plaisir de travailler en sa pr√©sence, elle apporte beaucoup d'√©nergie o√π qu'elle aille."
      #image: 
    - name: 
      #designation: 
      content: "Le rapport gain / prix vaut vraiment le coup niveau volume et impact pour l'app !"
      #image: 
    - name: 
      #designation: 
      content: "Alexia a syst√©matiquement su adapter sa m√©thode et ses √©quipes dans un univers technologique et strat√©gie √©voluant tr√®s rapidement, tout en conservant un niveau d'exigence √©lev√©."
      #image: 
    - name: 
      #designation: 
      content: "Alexia est une personne √† l'√©coute, organis√©e et tr√®s dynamique, toujours avec une √©nergie positive et une bonne humeur communicative."
      #image:
    - name: 
      #designation: 
      content: "Son professionnalisme et son engagement font d'elle une collaboratrice pr√©cieuse avec qui il est un vrai plaisir de travailler."
      #image:



#-------------------------------
# Author resume

author_info:
  resume_title: "<span class=\"text-span\">R√©sum√©</span>"
  accueil: "üëã Tu donnes tout pour cr√©er une solution innovante et vertueuse, mais les utilisateur.ices ne sont pas au rendez-vous, les priorit√©s s'accumulent et/ou les √©quipes sont perdues. Tu es au bon endroit !"
  objective: "<strong>Objectif :</strong> concevoir en harmonie des produits / services que les gens adoptent durablement et recommandent avec enthousiasme !"
  profile: "<strong>Profil :</strong> Psychologue cognitiviste avec 15 ans d'exp√©rience dans la tech, Certifi√©e \"√©coconception de service num√©rique\" üåø"
  services: "<strong>Accompagnement :</strong> UX Design, Product Management et DesignOps."
  product_type: "<strong>Type de produits / services :</strong> num√©rique (ex : apps, logiciels, plateformes) et physique (ex : domotique, robotique) | B2B / B2C | innovation, gamification, immersion, maps."
  mission_duration: "<strong>Dur√©e de missions :</strong> d'une demi-journ√©e √† plusieurs semaines / mois (en plein temps ou partiel)."
  companies: "<strong>Entreprises :</strong> startups/entreprises innovantes √† impact environnemental ou social avec des √©quipes pluridisciplinaires."
  languages: "<strong>Langues :</strong> fran√ßais / anglais."
  area: "<strong>Zone g√©ographique :</strong> r√©gion de Paris et distanciel."
  # calltoaction: "ü§© Travaillons ensemble !"

#-------------------------------
# Author clients


#-------------------------------
# Author pitch

#author_quiz:
  #description: "Si toi aussi tu aimes jouer, tu peux en apprendre plus gr√¢ce √† ce <strong><a href='https://team-planet.com/fr' style='text-decoration: underline;' target='_blank'>quiz</a> </strong> et tenter de gagner une r√©duc üòÅ"


#-------------------------------
# Author pitch

author_pitch:
  statements:
    - description: üß† Psychologue cognitiviste de formation, l'humain est au coeur de mon expertise.

    - description: üí™ J'accompagne les startups/entreprises innovantes et impactantes qui ne peuvent pas avoir d'UX Designer √† plein temps, ou qui ont besoin d'un regard ext√©rieur. 

    - description: üåø Certifi√©e "√©coconception de service num√©rique", je prends en compte les probl√©matiques environnementale dans mes recommandations. 

    - description: "üïä Je vise l'harmonie : que ce soit entre vos utilisateurs et votre produit, ou entre les membres de vos √©quipes."

    - description: ü§© Travaillons ensemble ! 


#--------------------------------
# Section with 3 Columns Valeurs
columns_section:
  bigtitle: Mes <span class="text-span">valeurs</span> pour √™tre utile et pertinente
  column:
   - title: "Adaptation"
     description: "Je m'adapte √† votre r√©alit√© : produit, cible, d√©lais, ressources, etc."
     image: "ü¶é"
     image_alt: "Ic√¥ne d'un cam√©l√©on"

   - title: "Efficacit√©"
     description: "Je vise la frugalit√© en trouvant des moyens et des solutions simples et efficaces."
     image: "ü¶´"
     image_alt: "Ic√¥ne d'un castor"

   - title: "Confiance"
     description: "J'aime accompagner les m√™mes √©quipes dans une relation positive et de confiance."
     image: "üêù"
     image_alt: "Ic√¥ne d'une abeille"


#-------------------------------
# Interventions

interventions:
  title: "Domaines d'<span class=\"text-span\">intervention</span>"
  items:
   - subtitle: "UX / Product Design"
     description: "L'exp√©rience doit √™tre positive avec des interactions intuitives, efficaces, efficientes et satisfaisantes, √† toutes les √©tapes du parcours produit."
     items:
       - "<strong>üòå Pour les pr√©voyant.e.s :</strong> en amont du d√©veloppement pour adopter la bonne strat√©gie pour les utilisateurs.rices."
       - "<strong>ü§† Pour les press√©.e.s :</strong> audit et recommandations sur l'exp√©rience de votre produit."
       - "<strong>ü´† Pour les submerg√©.e.s :</strong> identifier avec du recul ce qui a vraiment de la valeur pour l'exp√©rience de votre produit."
       - "<strong>üëØ Pour du renfort :</strong> UX Design complet d'une feature ou d'un produit (analyse des besoins, benchmark, user journey, wireframes, sp√©cifications, suivi d'impl√©mentation‚Ä¶)."
     tools: "<strong>Outils :</strong> Figma, FigJam, Notion, Miro, Mixpanel, Gsuite, Microsoft Office et leurs √©quivalents." 

   - subtitle: "Product Management"
     description: "Au m√™me titre que le produit, l'exp√©rience de travail doit √™tre positive, efficace et satisfaisante pour tous les membres de l'√©quipe."
     items:
      - "<strong>üöÄ Vision produit :</strong> d√©finir et encadrer la vision produit, garantir l'ad√©quation du produit avec cette vision."
      - "<strong>üóìÔ∏è Roadmapping :</strong> int√©grer les retours notamment utilisateurs, prioriser les d√©veloppements, communiquer et planifier avec l'√©quipe."
      - "<strong>üìù Specs :</strong> sp√©cifier des fonctionnalit√©s ou corner cases."
      - "<strong>‚öôÔ∏è Process :</strong> concevoir des process adapt√©s (workflow, rituels, outils‚Ä¶)."
     tools: "<strong>Outils :</strong> Notion, FigJam, Miro, Mixpanel, Trello, GitLab, JIRA et leurs √©quivalents."

   - subtitle: "DesignOps"
     description: "Evaluation et recommandations pour fluidifier les process et harmoniser la collaboration entre les √©quipes Design, Tech et Produit."
     items:
      - "<strong>üëê Workshop :</strong> intervention rapide et macro avec observations, rencontres avec les √©quipes, identification des pain points et proposition d'am√©liorations."
      - "<strong>üîé Audit complet :</strong> intervention plus longue avec des rencontres en groupe et/ou des entretiens individuels, √©valuation des process actuels et √©laboration d'un workflow personnalis√© suivi d'it√©rations avec les √©quipes."
   
   - subtitle: "Bon √† savoir"
     description: "J'ai un <strong>excellent contact</strong> avec les √©quipes tech üßë‚Äçüíª<br/>Je comprends bien les probl√®matiques techniques pour trouver des compromis en bonne collaboration. Merci √† mes anciens coll√®gues de m'avoir fait monter en comp√©tences sur ces sujets !<br/><br/>Je ne fais pas de Direction Artistique ou UI Design üé® <br/>L'esth√©tique d'un produit est tout aussi importante que son ergonomie. Ces 2 expertises sont compl√©mentaires mais quasi impossibles √† ma√Ætriser profond√©ment par une m√™me personne.<br/>Si vous avez √©galement ce besoin, je connais des personnes g√©niales avec qui j'ai l'habitude de <strong>travailler en bin√¥me</strong> !"

#-------------------------------
# Community section

community:
  title: "<span class=\"text-span\">Communaut√©s</span>"
  items:
    - name: "Team for the Planet"
      description: "Team for the Planet rassemble de l'argent pour d√©tecter et d√©ployer 100 innovations mondiales contre les gaz √† effet de serre."
      link: "https://team-planet.com/fr"
      logo: "/images/communities/team-planet.png"
    
    - name: "Climate House"
      description: "La Climate House est une maison qui rassemble des entrepreneurs, entreprises, investisseurs, associations, activistes, chercheurs, scientifiques, √©tudiants... Ces architectes de demain, quels que soient les freins auxquels ils sont confront√©s ‚Äî financement, visibilit√©, technologie ou r√©glementation ‚Äî pourront, s'inspirer les uns les autres, et ensemble maximiser et acc√©l√©rer leur impact."
      link: "https://climate.house/"
      logo: "/images/communities/climate-house.png"
    
    - name: "Freelance For Good"
      description: "Social Declik est un collectif d'ind√©pendants qui proposent leurs comp√©tences au service du bien commun pour aider des entreprises engag√©es √† r√©soudre des probl√©matiques environnementales ou soci√©tales."
      link: "https://socialdeclik.com/"
      logo: "/images/communities/social-declik.png"
    
    - name: "The Impact Circle"
      description: "The Impact Circle est une communaut√© qui facilite le partage de connaissances, √©largit les r√©seaux et augmente notre impact collectif au sein de l'√©cosyst√®me entrepreneurial √† impact."
      link: "https://theimpactcircle.fr/"
      logo: "/images/communities/impact-circle.jpg"
   #- "<strong><a href='https://team-planet.com/fr' style='text-decoration: underline;'>L'Opservatoire :</strong> l'Harmonie üïä"

#-------------------------------
# M√©cenat section

mecenat:
  title: "<span class=\"text-span\">M√©c√©nat de comp√©tences</span>"
  items:
   - "<strong><a href='https://initiatives.theshifters.org/initiative/I20240714191246/' style='text-decoration: underline;' target='_blank'>Les Shifters</a> :</strong> Dans le cadre de la Grande Consultation du Sport, je suis volontaire pour conduire des entretiens qualitatifs avec des sportifs amateurs et rapporter leurs r√©sultats."
   - "<strong><a href='https://www.innoverpourlatransitionecologique.fr/fr/challenges/open-booster' style='text-decoration: underline;' target='_blank'>Agence Fran√ßaise de D√©veloppement</a> :</strong> Dans le cadre du Challenge de l'Open Booster de l'Initiative Adapt'Action, j'ai √©t√© volontaire UX Designer et cheffe de projet pour Notre Logi'eau."
   - "<strong><a href='https://startupforkids.fr/programme-change-makher/' style='text-decoration: underline;' target='_blank'>Change Mak'Her</a> :</strong> mentor pour ce programme pour les jeunes filles de 13 √† 18 ans : un accompagnement d'un an pour cr√©er un projet num√©rique √† impact !"
   #- "<strong><a href='https://team-planet.com/fr' style='text-decoration: underline;'>L'Opservatoire :</strong> l'Harmonie üïä"
   - "N'h√©sitez pas √† me contacter pour vous aider !"

#-------------------------------
# Projects Settings

#projects__settings:
#  projects__title: Latest <span class="text-span">Works</span> # Add a 'text-span' class to highlight text.
#  projects__description: I shows only the best websites and portfolios built completely with passion, simplicity & creativity!


#-------------------------------
# Testimonials Section

#testimonial__title: My Happy <span class="text-span">Clients</span> # Add a 'text-span' class to highlight text.

#testimonial-items:
#  - name: "Zaire Baptista"
#    image: "/images/client-1.jpg"
#    designation : "Traveler"
#    content : "Quamquam id quidem, infinitum est in hac urbe, Ita multo sanguine profuso in laetitia et in victoria est mortuus. Atqui pugnantibus et contrariis consiliisque."
#
#  - name: "Ann Philips"
#    image: "/images/client-2.jpg"
#    designation : "Designer"
#    content : "Quamquam id quidem, infinitum est in hac urbe, Ita multo sanguine profuso in laetitia et in victoria est mortuus. Atqui pugnantibus et contrariis consiliisque."
#
#  - name: "Roger Bergson"
#    image: "/images/client-3.jpg"
#    designation : "CEO, Founder"
#    content : "Quamquam id quidem, infinitum est in hac urbe, Ita multo sanguine profuso in laetitia et in victoria est mortuus. Atqui pugnantibus et contrariis consiliisque."
#
#  - name: "Julie Arnold"
#    image: "/images/client-4.jpg"
#    designation : "Full stack developer"
#    content : "Quamquam id quidem, infinitum est in hac urbe, Ita multo sanguine profuso in laetitia et in victoria est mortuus. Atqui pugnantibus et contrariis consiliisque."


#-------------------------------
# Blog Section

blog__settings:
  blog__title: Derniers <span class="text-span">partages</span> d'exp√©rience # Add a 'text-span' class to highlight text.
  blog__description:


#-------------------------------
# Contact Settings

contact__settings:
  contact__email: your@email.com # Add your email for contact form
  contact__title: <span class="text-span">Get</span> in touch # Add a title to your form
  contact__description: Avenco comes with a built-in contact form. # Add a description to your form

# NOTE
# Avenco comes with a built-in contact form, that you can use with Formspree service to handle up to 50 submissions per month for free. You could also easily switch to another contact form service if you want.


#-------------------------------
# Newsletter Settings
# mailchimp__settings:
  #mailchimp__title: <span class="text-span">Join</span> my mailing list # Add your title
  #mailchimp__text: " 'Get inspiration, updates and', 'cool stuff about design!' " # Add descriptions to the form by wrapping the text in single quotes. If you want to use more than one sentence, be sure to separate them with a comma.
  #mailchimp__identifier: # Add your MailChimp form identifier. For example - blogenjoyfreedom.us16.list-manage.com/subscribe/post?u=cd56155d76ddeeb4c0bc4d080&amp;id=7a526cd13e
  #mailchimp__button__text: Subscribe # Add your button text


#-------------------------------
# Comment Section (Disqus)
# disqus-identifier: anvodstudio-demo # add your shortname for Disqus Comment. For example anvodstudio-demo


#-------------------------------
# Google Analytics
google-analytics: # Add your identifier. For example UA-99631805-1.


#-------------------------------
# Footer Settings
# Social Links
# Example of adding a new link to the footer - {icon: "ion-logo-facebook", link: "https://facebook.com"}
# Other icons can be found at https://ionicons.com/v4/
social:
- {icon: "ion-logo-linkedin", link: "https://www.linkedin.com/in/alexiabuclet/"}
- {icon: "ion-logo-instagram", link: "https://www.instagram.com/alexiabuclet/"}
- {icon: '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 21 21" width="21" height="21"><path fill="currentColor" d="M13.54 12a6.8 6.8 0 01-6.77 6.82A6.8 6.8 0 010 12a6.8 6.8 0 016.77-6.82A6.8 6.8 0 0113.54 12zM20.96 12c0 3.54-1.51 6.42-3.38 6.42-1.87 0-3.39-2.88-3.39-6.42s1.52-6.42 3.39-6.42 3.38 2.88 3.38 6.42M24 12c0 3.17-.53 5.75-1.19 5.75-.66 0-1.19-2.58-1.19-5.75s.53-5.75 1.19-5.75C23.47 6.25 24 8.83 24 12z"/></svg>', link: "https://medium.com/@alexia.buclet"}
#- {icon: "ion-logo-twitter", link: "https://x.com/alexiabuclet"}
#- {icon: '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width="21" height="21"><path d="M0 4.48v15.04h24V4.48H0zM18 10.09c0 .85-.68 1.53-1.53 1.53H15.6v3.81h.77c.85 0 1.53.68 1.53 1.53s-.68 1.53-1.53 1.53H15.6v2.02h-2.02v-2.02h-1.53c-.85 0-1.53-.68-1.53-1.53s.68-1.53 1.53-1.53h1.53v-3.81h-1.53c-.85 0-1.53-.68-1.53-1.53s.68-1.53 1.53-1.53h1.53V6.5h2.02v3.59H18v1.53z"/></svg>', link: "https://www.behance.net/AlexiaBuclet"}
- {icon: "ion-logo-youtube", link: "https://www.youtube.com/@alexiabuclet"}
#- {icon: "ion-logo-github", link: "https://github.com"}
#- {icon: "ion-logo-pinterest", link: "https://pinterest.com"}
#- {icon: "ion-logo-codepen", link: "https://codepen.io"}
#- {icon: "ion-logo-vimeo", link: "https://vimeo.com"}

linkedin: https://www.linkedin.com/in/alexiabuclet/

