#-------------------------------
# Site Settings

title: Alexia Buclet
logo: # You can add own logo. For example '/images/logo.png'.
description: Senior UX / Product Designer & DesignOps Freelance pour projets Ã  impact

menu__settings:
  menu__items:
    - title: 'Home'
      url: '/'
    - title: 'Experience'
      url: '/projects/'
    - title: 'Speaker'
      url: '/blog/'
    - title: 'Pages'
      submenu:
      - url: '/about'
        title: 'About'
      - url: '/elements'
        title: 'Elements'

# Call to action button
cta__button__text: Contact

# Add global cover image (This field adds a background to the top and bottom of the site.)
cover__image: '/images/378.jpg'


#-------------------------------
# Author Settings

author:
  name: Alexia Buclet
  title: Alexia Buclet
  bio: Senior UX / Product Designer & DesignOps <br>Freelance pour projets Ã  impact ğŸŒ
  image: '/images/alexia-buclet.jpg'
  avatar: '/images/avatar.jpg'
  button__text: TO DEFINE
  # button in HTML


#-------------------------------
# Author resume

author_info:
  resume_title: "<span class=\"text-span\">RÃ©sumÃ©</span>"
  profile: "<strong>Profil :</strong> Psychologue cognitiviste ğŸ§  avec 14 ans d'expÃ©rience, CertifiÃ©e \"Ã©coconception de service numÃ©rique\" ğŸŒ¿"
  services: "<strong>Accompagnement :</strong> UX Design, Product Design et DesignOps."
  objective: "<strong>Objectif :</strong> lâ€™Harmonie ğŸ•Š que ce soit entre vos utilisateurs et votre produit, ou entre les membres de vos Ã©quipes."
  product_type: "<strong>Type de produits :</strong> numÃ©rique principalement (ex : apps, logiciels, sites web) mais physique possible (ex : domotique, robotique, packaging)."
  mission_duration: "<strong>DurÃ©e de missions :</strong> d'une demi-journÃ©e Ã  plusieurs semaines/mois (en plein temps ou partiel)."
  companies: "<strong>Entreprises :</strong> startups/entreprises innovantes et impactantes."
  # calltoaction: "ğŸ¤© Travaillons ensemble !"



#-------------------------------
# Author pitch

author_pitch:
  statements:
    - description: ğŸ§  Psychologue cognitiviste de formation, l'humain est au coeur de mon expertise.

    - description: ğŸ’ª J'accompagne les startups/entreprises innovantes et impactantes qui ne peuvent pas avoir dâ€™UX Designer Ã  plein temps, ou qui ont besoin dâ€™un regard extÃ©rieur. 

    - description: ğŸŒ¿ CertifiÃ©e "Ã©coconception de service numÃ©rique", je prends en compte les problÃ©matiques environnementale dans mes recommandations. 

    - description: "ğŸ•Š Je vise lâ€™harmonie : que ce soit entre vos utilisateurs et votre produit, ou entre les membres de vos Ã©quipes."

    - description: ğŸ¤© Travaillons ensemble ! 


#--------------------------------
# Section with 3 Columns Valeurs
columns_section:
  bigtitle: Mes <span class="text-span">valeurs</span> pour Ãªtre utile et pertinente
  column:
   - title: "Adaptation"
     description: "Je mâ€™adapte Ã  votre rÃ©alitÃ© : produit, cible, dÃ©lais, ressources, etc."
     image: "ğŸ¦"

   - title: "EfficacitÃ©"
     description: "Je vise la frugalitÃ© en trouvant des moyens et des solutions simples et efficaces."
     image: "ğŸ¦«"

   - title: "Confiance"
     description: "J'aime accompagner les mÃªmes Ã©quipes dans une relation positive et de confiance."
     image: "ğŸ"


#-------------------------------
# Interventions

interventions:
  title: "Domains d'intervention"
  items:
   subtitle: "UX / Product Design"
   description: "L'expÃ©rience vÃ©cue par les utilisateurs est dÃ©terminante pour un produit. Mon objectif est qu'elle soit positive en rendant les interactions intuitives, efficaces, efficientes et satisfaisantes, Ã  toutes les Ã©tapes d'utilisation du produit."
   items:
    - "<strong>ğŸ˜Œ Pour les prÃ©voyants :</strong> consultation en amont du dÃ©veloppement de votre produit pour aider Ã  vous orienter dans la bonne direction dâ€™un point de vue utilisateur."
    - "<strong>ğŸ¤  Pour les pressÃ©s :</strong> audit et recommandations sur lâ€™expÃ©rience de votre produit."
    - "<strong>ğŸ«  Pour les submergÃ©s :</strong> identifier avec du recul ce qui a vraiment de la valeur pour lâ€™expÃ©rience de votre produit. Ainsi vous pourrez vous concentrer sur lâ€™essentiel pour enfin dÃ©livrer la version tant attendue."
    - "<strong>ğŸ‘¯ Pour du renfort :</strong> UX Design complet dâ€™une feature ou dâ€™un produit (analyse des besoins, benchmark, user journey, wireframes, spÃ©cifications, suivi dâ€™implÃ©mentationâ€¦)."
  
   subtitle: DesignOps
   description: "Evaluation et recommandations pour fluidifier les process et harmoniser la collaboration dans les Ã©quipes Design, Tech et Produit. <br/> Sous forme de :"
   items:
    - "<strong>ğŸ‘ Workshop :</strong> intervention rapide et macro qui peut se composer dâ€™une rencontre avec les Ã©quipes pour comprendre les process actuels, identifier les pain points et en dÃ©gager des pistes dâ€™amÃ©lioration."
    - "<strong>ğŸ” Audit complet :</strong> intervention plus longue avec des rencontres en groupe et/ou des entretiens individuels avec les membres des Ã©quipes, Ã©valuation des process actuels et Ã©laboration dâ€™un workflow personnalisÃ© avec des itÃ©rations en collaboration avec les Ã©quipes."
  bonsavoir: "je ne fais pas du tout de Direction Artistique ou UI Design ğŸ¨ Je considÃ¨re que ce sont des mÃ©tiers qui demandent une expertise diffÃ©rente de la mienne (psychologie cognitive, tournÃ©e vers lâ€™humain ğŸ§ ).<br/>Lâ€™esthÃ©tique dâ€™un produit est tout aussi importante que son ergonomie, câ€™est pourquoi je pense que ces 2 expertises sont complÃ©mentaires mais quasi impossibles Ã  maÃ®triser profondÃ©ment par une mÃªme personne.""

#-------------------------------
# Projects Settings

projects__settings:
  projects__title: Latest <span class="text-span">Works</span> # Add a 'text-span' class to highlight text.
  projects__description: I shows only the best websites and portfolios built completely with passion, simplicity & creativity!


#-------------------------------
# Testimonials Section

testimonial__title: My Happy <span class="text-span">Clients</span> # Add a 'text-span' class to highlight text.

testimonial-items:
  - name: "Zaire Baptista"
    image: "/images/client-1.jpg"
    designation : "Traveler"
    content : "Quamquam id quidem, infinitum est in hac urbe, Ita multo sanguine profuso in laetitia et in victoria est mortuus. Atqui pugnantibus et contrariis consiliisque."

  - name: "Ann Philips"
    image: "/images/client-2.jpg"
    designation : "Designer"
    content : "Quamquam id quidem, infinitum est in hac urbe, Ita multo sanguine profuso in laetitia et in victoria est mortuus. Atqui pugnantibus et contrariis consiliisque."

  - name: "Roger Bergson"
    image: "/images/client-3.jpg"
    designation : "CEO, Founder"
    content : "Quamquam id quidem, infinitum est in hac urbe, Ita multo sanguine profuso in laetitia et in victoria est mortuus. Atqui pugnantibus et contrariis consiliisque."

  - name: "Julie Arnold"
    image: "/images/client-4.jpg"
    designation : "Full stack developer"
    content : "Quamquam id quidem, infinitum est in hac urbe, Ita multo sanguine profuso in laetitia et in victoria est mortuus. Atqui pugnantibus et contrariis consiliisque."


#-------------------------------
# Blog Section

blog__settings:
  blog__title: Recent <span class="text-span">Blog</span> Posts # Add a 'text-span' class to highlight text.
  blog__description:


#-------------------------------
# Contact Settings

contact__settings:
  contact__email: your@email.com # Add your email for contact form
  contact__title: <span class="text-span">Get</span> in touch # Add a title to your form
  contact__description: Avenco comes with a built-in contact form. # Add a description to your form

# NOTE
# Avenco comes with a built-in contact form, that you can use with Formspree service to handle up to 50 submissions per month for free. You could also easily switch to another contact form service if you want.


#-------------------------------
# Newsletter Settings
mailchimp__settings:
  mailchimp__title: <span class="text-span">Join</span> my mailing list # Add your title
  mailchimp__text: " 'Get inspiration, updates and', 'cool stuff about design!' " # Add descriptions to the form by wrapping the text in single quotes. If you want to use more than one sentence, be sure to separate them with a comma.
  mailchimp__identifier: # Add your MailChimp form identifier. For example - blogenjoyfreedom.us16.list-manage.com/subscribe/post?u=cd56155d76ddeeb4c0bc4d080&amp;id=7a526cd13e
  mailchimp__button__text: Subscribe # Add your button text


#-------------------------------
# Comment Section (Disqus)
disqus-identifier: anvodstudio-demo # add your shortname for Disqus Comment. For example anvodstudio-demo


#-------------------------------
# Google Analytics
google-analytics: # Add your identifier. For example UA-99631805-1.


#-------------------------------
# Footer Settings
# Social Links
# Example of adding a new link to the footer - {icon: "ion-logo-facebook", link: "https://facebook.com"}
# Other icons can be found at https://ionicons.com/v4/
social:
- {icon: "ion-logo-twitter", link: "https://twitter.com"}
- {icon: "ion-logo-github", link: "https://github.com"}
- {icon: "ion-logo-pinterest", link: "https://pinterest.com"}
- {icon: "ion-logo-codepen", link: "https://codepen.io"}
- {icon: "ion-logo-vimeo", link: "https://vimeo.com"}
- {icon: "ion-logo-youtube", link: "https://youtube.com"}